let obj = {
  ar: [
    {
      sem1: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem2: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem3: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem4: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem5: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem6: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem7: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem8: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem9: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem10: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ]
    },
  ],
  bme: [
    {
      sem1: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem2: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem3: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem4: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem5: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem6: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem7: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem8: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
    },
  ],
  bt: [
    {
      sem1: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem2: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem3: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem4: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem5: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem6: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem7: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem8: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
    },
  ],
  che: [
    {
      sem1: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem2: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem3: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem4: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem5: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem6: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem7: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem8: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
    },
  ],
  civ: [
    {
      sem1: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem2: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem3: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem4: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem5: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem6: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem7: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem8: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
    },
  ],
  min: [
    {
      sem1: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem2: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem3: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem4: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem5: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem6: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem7: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem8: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
    },
  ],
  cse: [
    {
      sem1: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem2: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem3: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem4: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem5: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem6: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem7: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem8: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
    },
  ],
  ele: [
    {
      sem1: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem2: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem3: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem4: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem5: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem6: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem7: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem8: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
    },
  ],
  ece: [
    {
      sem1: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem2: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem3: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem4: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem5: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem6: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem7: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem8: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
    },
  ],
  it: [
    {
      sem1: [
        { name: "MathematicsI", credits: 4, expectedGrade: 9 },
        { name: "PhysicsI", credits: 3, expectedGrade: 9 },
        { name: "AppliedChemistry", credits: 3, expectedGrade: 9 },
        { name: "CommunicationSkills", credits: 3, expectedGrade: 9 },
        { name: "EngineeringGraphics", credits: 3, expectedGrade: 9 },
        { name: "ValueEducation", credits: 1, expectedGrade: 9 },
        { name: "AppliedChemistryLab", credits: 1, expectedGrade: 9 },
        { name: "CommunicationSkillsLab", credits: 1, expectedGrade: 9 },
        { name: "Workshop", credits: 2, expectedGrade: 9 },
        { name: "PhysicsILab", credits: 1, expectedGrade: 9 },
        { name: "EngineeringGraphicsLab", credits: 1, expectedGrade: 9 },
        { name: "YogaandHealth", credits: 1, expectedGrade: 9 },
      ],
      sem2: [
        { name: "MathematicsII", credits: 4, expectedGrade: 9 },
        { name: "PhysicsII", credits: 3, expectedGrade: 9 },
        { name: "EnvironmentandEcology", credits: 3, expectedGrade: 9 },
        { name: "Computerprogramming", credits: 3, expectedGrade: 9 },
        { name: "DataStructure", credits: 3, expectedGrade: 9 },
        { name: "BasicElectricalEngineering", credits: 3, expectedGrade: 9 },
        { name: "ComputerprogrammingLab", credits: 1, expectedGrade: 9 },
        { name: "PhysicsIILab", credits: 1, expectedGrade: 9 },
        { name: "EnvironmentandEcologyLab", credits: 1, expectedGrade: 9 },
        { name: "DataStructureLab", credits: 1, expectedGrade: 9 },
        { name: "BasicElectricalEngineeringLab", credits: 1, expectedGrade: 9 },
        { name: "NCC/NSS", credits: 0, expectedGrade: 9 },
      ],
      sem3: [
        { name: "Discrete structures ", credits: 4, expectedGrade: 9 },
        {
          name: "digital electronics and logic design",
          credits: 4,
          expectedGrade: 9,
        },
        {
          name: "object oriented methodology 4 communication systems ",
          credits: 4,
          expectedGrade: 9,
        },
        { name: "operating systems ", credits: 4, expectedGrade: 9 },
        { name: "mathematics-III ", credits: 4, expectedGrade: 9 },
        { name: "oops lab ", credits: 1, expectedGrade: 9 },
        { name: "operating system lab", credits: 1, expectedGrade: 9 },
      ],
      sem4: [
        { name: "Computer organization", credits: 4, expectedGrade: 9 },
        { name: "theory of computation", credits: 4, expectedGrade: 9 },
        { name: "database management system", credits: 4, expectedGrade: 9 },
        { name: "Internet and web technologies", credits: 4, expectedGrade: 9 },
        { name: "software engineering", credits: 4, expectedGrade: 9 },
        { name: "mathematics-IV", credits: 4, expectedGrade: 9 },
        { name: "dbms lab", credits: 1, expectedGrade: 9 },
        { name: "web technology la", credits: 1, expectedGrade: 9 },
      ],
      sem5: [
        { name: "Design Analysis of Algorithms", credits: 4, expectedGrade: 9 },
        { name: "Computer Networks", credits: 4, expectedGrade: 9 },
        { name: "Data Mining", credits: 4, expectedGrade: 9 },
        { name: "Program Elective – I", credits: 3, expectedGrade: 9 },
        { name: "Open Elective - I", credits: 3, expectedGrade: 9 },
        {
          name: "Design Analysis of Algorithms Lab",
          credits: 1,
          expectedGrade: 9,
        },
        { name: "Computer Networks", credits: 1, expectedGrade: 9 },
        { name: "Summer Internship", credits: 1, expectedGrade: 9 },
      ],
      sem6: [
        { name: "Compiler Design", credits: 4, expectedGrade: 9 },
        { name: "Artificial Intelligence", credits: 4, expectedGrade: 9 },
        { name: "Computer Graphics", credits: 4, expectedGrade: 9 },
        { name: "Program Elective-II", credits: 3, expectedGrade: 9 },
        { name: "Open Elective-II", credits: 3, expectedGrade: 9 },
        { name: "Artificial Intelligence Lab", credits: 1, expectedGrade: 9 },
        { name: "Computer Graphics Lab", credits: 1, expectedGrade: 9 },
      ],
      sem7: [
        { name: "Internet of Things", credits: 4, expectedGrade: 9 },
        { name: "Program Elective - III", credits: 3, expectedGrade: 9 },
        { name: "Program Elective - IV", credits: 3, expectedGrade: 9 },
        { name: "Open Elective - III", credits: 3, expectedGrade: 9 },
        { name: "Internet of Things Lab", credits: 1, expectedGrade: 9 },
        { name: "Project Work ", credits: 4, expectedGrade: 9 },
        { name: "Summer Internship II", credits: 2, expectedGrade: 9 },
      ],
      sem8: [
        { name: "Program Elective - V", credits: 3, expectedGrade: 9 },
        { name: "ProgramElective - VI", credits: 3, expectedGrade: 9 },
        { name: "Open Elective - IV", credits: 3, expectedGrade: 9 },
        { name: "Open Elective - V", credits: 3, expectedGrade: 9 },
      ],
    },
  ],
  me: [
    {
      sem1: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem2: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem3: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem4: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem5: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem6: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem7: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem8: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
    },
  ],
  mme: [
    {
      sem1: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem2: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem3: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem4: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem5: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem6: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem7: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem8: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
    },
  ],
  ca: [
    {
      sem1: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem2: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem3: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem4: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem5: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ],
      sem6: [
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
        { name: "subject-X", credits: 0, expectedGrade: 9 },
      ]
    },
  ],
};
const prevTotalCreditsOptions = {"ar":{  1:25,  2:25,  3:24,  4:24,  5:24,  6:24,  7:24,  8:6,  9:20,  10:20},"bme":{  1:24,  2:24,  3:26,  4:26,  5:21,  6:20,  7:20,  8:12},"bt":{  1:24,  2:24,  3:26,  4:26,  5:21,  6:20,  7:20,  8:12},"ca":{  1:24,  2:24,  3:24,  4:23,  5:19,  6:20,},"che":{  1:24,  2:24,  3:26,  4:26,  5:21,  6:20,  7:20,  8:12},"civ":{  1:24,  2:24,  3:26,  4:26,  5:21,  6:20,  7:20,  8:12},"cse":{  1:24,  2:24,  3:26,  4:26,  5:21,  6:20,  7:20,  8:12},"ece":{  1:24,  2:24,  3:26,  4:26,  5:21,  6:20,  7:20,  8:12},"ele":{  1:24,  2:24,  3:26,  4:26,  5:21,  6:20,  7:20,  8:12},"it":{  1:24,  2:24,  3:26,  4:26,  5:21,  6:20,  7:20,  8:12},"me":{  1:24,  2:24,  3:26,  4:26,  5:24,  6:20,  7:20,  8:12},"min":{  1:24,  2:24,  3:26,  4:26,  5:21,  6:20,  7:20,  8:12},"mme":{  1:24,  2:24,  3:26,  4:26,  5:21,  6:20,  7:20,  8:12}};
export {obj,prevTotalCreditsOptions};
